
spring:
  jpa:
    generate-ddl: true
    show-sql: true
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
debug: true
logging:
  level:
     org:
       hibernate:
         type: TRACE

